version : "3"

services:
  voos:
    image: imagevoos
    build: .
    volumes:
      - "./servicos/voos:/servicos"
    command: python3 servico.py
    expose:
      - "5000"
    networks:
      mynet:
        ipv4_address: "172.28.1.1"

  compra:
    image: imagevoos
    build: .
    volumes:
      - "./servicos/compra:/servicos"
    command: python3 servico.py
    expose:
      - "5000"
    networks:
      mynet:
        ipv4_address: "172.28.1.2"
  
  checkin:
    image: imagevoos
    build: .
    volumes:
      - "./servicos/checkin:/servicos"
    command: python3 servico.py
    expose:
      - "5000"
    networks:
      mynet:
        ipv4_address: "172.28.1.3"


  banco_volatil:
    image: memcached
    hostname: banco_volatil
    expose: 
      - "11211"
    networks:
      mynet:
        ipv4_address: "172.28.1.11"

networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: "172.28.1.0/16"